[package]
name = "passmaker"
version = "0.1.0"
authors = ["ussr"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mimalloc = { version = "0.1", default-features = false }
rand = "0.8"
